In [1]:
import pandas

In [8]:
import spacy

In [9]:
# initialize language model
nlp = spacy.load("en_core_web_md")

# add pipeline (declared through entry_points in setup.py)
linker = nlp.add_pipe("entityLinker", last=True)

In [3]:
system_census = pandas.read_excel('FY22 System Census - API AI Software Products_2022_0128.xlsx', 
                                  sheet_name="System Software Products")

In [32]:
entities = []
for mention in system_census['Product Name'].value_counts().index:
    doc = nlp(mention)
    if doc._.linkedEntities:
        for ent in doc._.linkedEntities:
            entities.append({
                'Produc Name': mention,
                'wd_id': f'Q{ent.identifier}',
                'wd_label': ent.label,
                'wd_desc': ent.description
            })
            break
    else:
        entities.append({
            'Produc Name': mention,
        })

In [34]:
pandas.DataFrame(entities).head(50)

,Produc Name,wd_id,wd_label,wd_desc
0,Enterprise Linux (Server),Q388,Linux,operating system family that use the Linux ker...
1,SQL Server,Q215819,Microsoft SQL Server,family of database software
2,Database,Q5227381,Database,online peer-reviewed open access scientific jo...
3,Windows Server 2012,Q11219,Windows Server,brand name for a group of server operating sys...
4,PostgreSQL,Q192490,PostgreSQL,Free and open-source relational database manag...
5,Tomcat,Q34945,F-14 Tomcat,carrier-based air superiority fighter aircraft...
6,MySQL,Q850,MySQL,SQL database engine software
7,Java Development Kit (JDK),Q741303,Java Development Kit,implementation of either one of the Java Platf...
8,Internet Information Services (IIS),Q11341,Internet Information Services,"Microsoft's web server software, included in m..."
9,Application Server,Q44127,server,computer program or device that provides acces...
10,Jenkins,Q7491312,Jenkins,continuous integration tool
11,Splunk,Q1835753,Splunk,None
12,Windows Server 2016,Q11219,Windows Server,brand name for a group of server operating sys...
13,Simple Storage Service (Amazon S3),Q7520642,Simple,A bank
14,HTTP Server,Q11288,web server,server that serves website content to clients
15,Relational Database Service (Amazon RDS),Q3479121,Service,2008 film by Brillante Mendoza
16,nginx,Q306144,nginx,open source web server and a reverse proxy server
17,MQ,Q17054,Martinique,"island in the Lesser Antilles, overseas region..."
18,Enterprise COBOL for z/OS,Q369987,USS Enterprise,1938 Yorktown-class aircraft carrier of the Un...
19,Elastic Compute Cloud (Amazon EC2),Q5135628,Cloud,American dancer
20,z/OS,NaN,NaN,NaN
21,AWS Lambda,Q21462856,AWS Lambda,"event-driven, serverless computing platform pr..."
22,Python,Q28865,Python,"general-purpose, high-level programming language"
23,SonarQube,Q541691,SonarQube,open-source platform for continuous inspection...
24,Ansible,NaN,NaN,NaN
25,Analytics (SAS Analytics),Q25221941,Analytics,None
26,Terraform,Q28957072,Terraform,software
27,Server (Tableau Server),Q37066363,Server,family name
28,Drupal,Q170855,Drupal,web content management system
29,Connect:Direct,NaN,NaN,NaN
30,.NET Framework,Q5289,.NET Framework,software platform developed by Microsoft
31,Node.js,Q756100,Node.js,Server-side JavaScript framework
32,DB2,NaN,NaN,NaN
33,Kong,Q216810,King Kong,"fictional character, a giant movie monster res..."
34,API Gateway,Q165194,application programming interface,"set of subroutine definitions, protocols, and ..."
35,Enterprise (GitHub Enterprise),Q369987,USS Enterprise,1938 Yorktown-class aircraft carrier of the Un...
36,PowerCenter,NaN,NaN,NaN
37,Docker,Q15206305,Docker,open-source software for deploying application...
38,Elastic MapReduce (Amazon EMR),Q567759,MapReduce,programming model for efficient queries over h...
39,Enterprise Application Platform,Q369987,USS Enterprise,1938 Yorktown-class aircraft carrier of the Un...
40,Linux 2,Q388,Linux,operating system family that use the Linux ker...
41,HTTP Server for WebSphere Application Server H...,Q37066363,Server,family name
42,CloudWatch,NaN,NaN,NaN
43,Endevor Software Change Manager (SCM),Q3090589,Change.org,petition website
44,MicroStrategy (MicroStrategy BI Platform),Q1192211,MicroStrategy,American technology company
45,AWS Identity and Access Management (IAM),Q468565,Management,2008 American romantic comedy-drama directed b...
46,Linux,Q388,Linux,operating system family that use the Linux ker...
47,Redshift,NaN,NaN,NaN
48,JAWS,Q1676557,JAWS,screen reader
49,Connect:Direct for z/OS,Q9751,Z,letter of the Latin alphabet

In [37]:
system_census[['Product Manufacturer', 'Product Name', 'Product Type']].drop_duplicates()

,Product Manufacturer,Product Name,Product Type
0,PHP Group,PHP,Software Development
1,Oracle,MySQL,Database Management Systems (DBMS)
2,Jenkins CI,Jenkins,Software Development
3,Taylor Otwell,Laravel,Software Development
4,Memcached Project,Memcached,Storage Management
...,...,...,...
2449,Seagull,BarTender,Enterprise Content Management (ECM)
2451,Actian,PSQL,Database Management Systems (DBMS)
2458,Hwaci,SQLite,Database Management Systems (DBMS)
2461,Eclipse Foundation,PHP Development Tools (PDT),Software Development
2462,axios,axios,Software Development